import { Summary } from '@/components/Home/Summary';
import { Header } from '@/components/Home/Header';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Habits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen px-7 lg:px-0">
        <div className="w-full h-full flex flex-col items-center justify-center gap-[70px]">
          <Header />
          <Summary />
        </div>
      </main>
    </>
  );
}
